import { Layout } from "@/components/ui";
import { Ubuntu } from "next/font/google";
import "./globals.css";

const ubuntuFont = Ubuntu({
    subsets: ["latin"],
    weight: ["400", "500", "700"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en">
            <body className={ubuntuFont.className}>
                <Layout>{children}</Layout>
            </body>
        </html>
    );
}
